# Generated by Django 6.0.4 on 2026-04-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En Préstamo', 'En Préstamo'), ('Mantenimiento', 'Mantenimiento'), ('Baja', 'Baja')], default='Disponible', max_length=20)),
                ('cantidad_total', models.PositiveIntegerField(default=1)),
                ('cantidad_disponible', models.PositiveIntegerField(default=1)),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='labs.laboratorio')),
            ],
            options={
                'ordering': ('nombre', 'numero_serie'),
            },
        ),
    ]
