# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("estudiante", "Estudiante"),
                    ("tecnico", "Técnico"),
                    ("admin", "Administrador"),
                    ("personal", "Personal"),
                ],
                default="estudiante",
                max_length=20,
            ),
        ),
    ]
