# Generated by Django 6.0.4 on 2026-04-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('edificio', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=80)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En Mantenimiento', 'En Mantenimiento'), ('Ocupado', 'Ocupado')], default='Disponible', max_length=20)),
                ('equipamiento', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
    ]
