# Generated by Django 6.0.4 on 2026-04-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('horario', models.CharField(max_length=20)),
                ('proyecto', models.CharField(max_length=200)),
                ('motivo', models.TextField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Devuelto', 'Devuelto')], default='Pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='equipment.equipo')),
            ],
            options={
                'ordering': ('fecha', 'horario', 'equipo__nombre'),
            },
        ),
    ]
